---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
    app: backend
  name: devops-backend
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: api
    port: 8080
    targetPort: 8080