---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
    app: frontend
  name: devops-frontend
  namespace: dev
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: api
    port: 3000
    targetPort: 3000
